install:
  - ps: Install-Product node 0
  - npm install

test_script:
  - node --version
  - npm --version

build_script:
  - npm run build:electron -- --runtime-version=0.33.3
  - npm pack
  - dir

deploy:
  description: 'A release'
  provider: GitHub
  artifact: /.*\.tgz/
  auth_token:
    secure: 43dm1ty9okNNWNCYCNEddhKnkCXS8wOxV9UA+J0WbUPVwWAzsThCqaenRa/1ZPij
  on:
    branch: master
    appveyor_repo_tag: true
