environment:
  GITHUB_OAUTH_TOKEN:
    secure: OqCUsed8DRsFueq2Ct/86kB8z18IdC+9NfVc1ERHYE4oqC146yUCjfCxVQJ/63xQ

version: {branch}-{build}

platform:
  - x86
  - x64

configuration:
  - Release

install:
  - ps: Install-Product node 0
  - npm install

test_script:
  - node --version
  - npm --version

build_script:
  - npm run build:electron -- --runtime-version=0.33.3
  - npm pack
  - dir

on_success:
  - node upload.js

artifacts:
  - path: *.tgz

# deploy:
#   description: 'A release'
#   provider: GitHub
#   artifact: /.*\.tgz/
#   auth_token:
#     secure: OqCUsed8DRsFueq2Ct/86kB8z18IdC+9NfVc1ERHYE4oqC146yUCjfCxVQJ/63xQ
#   on:
#     branch: master
#     appveyor_repo_tag: true
